server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev_database?serverTimezone=UTC&useSSL=false
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath*:/mapping/*Mapper.xml
  type-aliases-package: com.ck.*